### ISSUE TITLE
Convert output with xcpretty

### ISSUE THREAD

**Issue by mgrebenets** [SiarheiFedartsou/fastlane-plugin-clang_analyzer#1]
It's more like a feature request.

Would it be OK to channel raw xcodebuild output to `xcpretty`?

Fastlane does it all the same, so `xcpretty` gem is already part of the setup.
Make it more readable that way.

The actual raw log can still be saved separately for troubleshooting if need to.

**Comment by SiarheiFedartsou** [comment]
@mgrebenets thanks for your proposition! I'll try to think about it.

**Comment by mgrebenets** [comment]
Resolved in `0.1.1`.
